name: Run Hourly Script

on:
  schedule:
    # Runs every day at 6:32 AM PT, 7:32 AM PT, 11:32 AM PT, 4:32 PM PT (specified here in UTC)
    - cron: '32 13,14,18,23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          MAILGUN_SEND_KEY: ${{ secrets.MAILGUN_SEND_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py